# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    parallelism: 1
    docker:
      # Other pre-built CI images https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn clean install
      - run: mvn test
      - codecov/upload:
          file: target/code-coverage-report/jacoco.xml
